# Generated by Django 5.2.7 on 2025-10-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual by Seller'), ('PARTNER', 'Third Party Partner')], max_length=10)),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_address', models.TextField(default='')),
                ('drop_address', models.TextField(default='')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='payments.escrowtransaction')),
            ],
        ),
    ]
