version: "3.8"

services:
  web:
    build: .
    container_name: escrow_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    container_name: escrow_worker
    command: celery -A escrow_service worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: escrow_redis
    ports:
      - "6379:6379"
